name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Rodar testes
      run: dotnet test --no-build --verbosity normal
