name: .NET API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies for API tests
      run: dotnet restore TodoListAPI.Tests/TodoListAPI.Tests.csproj

    - name: Build API tests
      run: dotnet build TodoListAPI.Tests/TodoListAPI.Tests.csproj --no-restore

    - name: Run unit tests
      run: dotnet test TodoListAPI.Tests/TodoListAPI.Tests.csproj --no-build --verbosity normal
